n = input('Digite algo: ')
s = type(n)
print('O tipo primitivo desse valor é {}'.format(s))
s1 = n.isspace()
print('Só tem espaços? {}'.format(s1))
s2 = n.isnumeric()
print('É um número? {}'.format(s2))
s3 = n.isalpha()
print('É alfabético? {}'.format(s3))
s4 = n.isalnum()
print('É alfanumérico? {}'.format(s4))
s5 = n.isupper()
print('Está em maiúsculas? {}'.format(s5))
s6 = n.islower()
print('Está em minúsculas? {}'.format(s6))
s7 = n.istitle()
print('Está capitalizada? {}'.format(s7))

